---
# This is the main playbook for windows deployment
# Specify the roles and variables for your targets
#

- name: Provision Windows system on VMware using API
  hosts: iis 
  become: yes
  gather_facts: no

  roles:
    - { role: add_host, when: state == 'present' }
    - { role: remove_host, when: state == 'absent' }

