---
# This play gathers the necessary facts to refresh our 
# core playbook information and contact our bootstrap partner
#

- name: Preparing for lab_builder
  hosts: localhost
  gather_facts: true
  become: yes
  become_method: sudo
  vars_prompt:
    - name: bootstrap_role
      prompt: "Enter the bootstrap role for this host. [build_master | foreman]"
      default: "build_master"
      private: no
    - name: bootstrap_fqdn
      prompt: "Enter the bootstrap FQDN for the local host"
      default: "buildmaster.labbuilder.lab"
      private: no
    - name: bootstrap_ip
      prompt: "Enter the bootstrap ipv4 address for the local host"
      default: "192.168.248.10"
      private: no
    - name: bootstrap_netmask
      prompt: "Enter the bootstrap network mask for the local host"
      default: "255.255.252.0"
      private: no
    - name: bootstrap_gateway
      prompt: "Enter the bootstrap gateway for the local host"
      default: "192.168.248.1"
      private: no
    - name: remote_bootstrap_fqdn
      prompt: "Enter the bootstrap FQDN for the REMOTE host"
      default: "foreman.labbuilder.lab"
      private: no
    - name: remote_bootstrap_ip
      prompt: "Enter the bootstrap ipv4 address for the REMOTE host"
      default: "192.168.248.12"
      private: no
    - name: redhat_org
      prompt: "Enter the Red Hat CDN organization"
      default: ""
      private: no
    - name: activation_key
      prompt: "Enter the Red Hat Activation Key for selected role"
      default: "build_master"
      private: no

  vars:
      satellite_pool: "Red Hat Satellite Infrastructure Subscription$"
      idm_pool: ""
      cdn_proxy_hostname: ""
      cdn_proxy_port: ""
      cdn_proxy_username: ""
      cdn_proxy_password: ""
      bootstrap_inventory_file: "{{ playbook_dir }}/inventory"

  tasks:

  - name: "Setting remote bootstrap role to foreman"
    set_fact:
      remote_bootstrap_role: "foreman"
    when: "bootstrap_role == 'build_master'"

  - name: "Setting remote bootstrap role to build_master"
    set_fact:
      remote_bootstrap_role: "build_master"
    when: "bootstrap_role == 'foreman'"

  - name: "Write out hosts file for bootstrap"
    blockinfile:
      path: "/etc/hosts"
      marker: "# {mark} ANSIBLE MANAGED BLOCK - prepare.yml"
      block: |
        {{ bootstrap_ip }}      {{ bootstrap_fqdn }}
        {{ remote_bootstrap_ip }}      {{ remote_bootstrap_fqdn }}

  - name: "Configuring local network."
    include_tasks: prepare_connect_network.yml

  - set_fact:
      subscription_pool: "{{ idm_pool }}" 
    when: "bootstrap_role == 'build_master'"

  - set_fact:
      subscription_pool: "{{ satellite_pool }}"
    when: "bootstrap_role == 'foreman'"

  - name: "Register the local system to the CDN"
    include_tasks: prepare_registration.yml

  - name: "Update the system"
    yum:
      name: "*"
      state: latest

# TODO:Pull the latest lab_builder here  
#
  - name: "Create bootstrap inventory file"
    file:
      path: "{{ bootstrap_inventory_file }}"
      state: touch 
    when: "bootstrap_role == 'build_master'"

  - name: "Write boostrap inventory for build_master"
    blockinfile:
      path: "{{ bootstrap_inventory_file }}"
      block: |
        # insert the buildmaster fqdn below
        # there can be only one during phase 1
        [build_master]
        {{ bootstrap_fqdn }}

        # insert the foreman fqdn below
        # there can be only one during phase 1
        [foreman]
        {{ remote_bootstrap_fqdn }}
    when: "bootstrap_role == 'build_master'"

  - name: "Create bootstrap_config file"
    file:
      path: "{{ playbook_dir }}/bootstrap_config"
      state: touch
      owner: root
      group: root
      mode: 400

  - name: "Write bootstrap_config file"
    blockinfile:
      path: "{{ playbook_dir }}/bootstrap_config"
      block: |
        bootstrap_role: "{{ bootstrap_role }}"
        bootstrap_fqdn: "{{ bootstrap_fqdn }}"
        bootstrap_ip: "{{ bootstrap_ip }}"
        bootstrap_netmask: "{{ bootstrap_netmask }}"
        bootstrap_gateway: "{{ bootstrap_gateway }}"
        remote_bootstrap_role: "{{ remote_bootstrap_role }}"
        remote_bootstrap_fqdn: "{{ remote_bootstrap_fqdn }}"
        remote_bootstrap_ip: "{{ remote_bootstrap_ip }}"
        redhat_org: "{{ redhat_org }}"
        activation_key: "{{ activation_key }}"

  - name: "NOTICE: Run ansible-playbook -i inventory site.yml on the 'build_master' after reboot."
    debug: 
      msg: "Reboot the system the system to continue."

