---
# Run the Satellite installer with the configured parameters.
# We will build up the command line in a variable
#

- name: Configure installer scenario
  set_fact: "installer_cmdline = {{ installer_cmdline }} --scenario={{ scenario }}"

- name: Configure compute resource - EC2
  set_fact: "installer_cmdline = {{ installer_cmdline }} --enable-foreman-compute-ec2=true"
  when: enable_ec2 == true

- name: Configure compute resource - GCE
  set_fact: "installer_cmdline = {{ installer_cmdline }} --enable-foreman-compute-gce=true" 
  when: enable_gce == true

- name: Configure compute resource - LibVirt
  set_fact: "installer_cmdline = {{ installer_cmdline }} --enable-foreman-compute-libvirt=true" 
  when: enable_libvirt == true

- name: Configure compute resource - OpenStack
  set_fact: "installer_cmdline = {{ installer_cmdline }} --enable-foreman-compute-openstack=true" 
  when: enable_openstack == true

- name: Configure compute resource - oVirt
  set_fact: "installer_cmdline = {{ installer_cmdline }} --enable-foreman-compute-ovirt=true" 
  when: enable_ovirt == true

- name: Configure compute resource - RackSpace
  set_fact: "installer_cmdline = {{ installer_cmdline }} --enable-foreman-compute-rackspace=true" 
  when: enable_rackspace == true

- name: Configure compute resource - VMware
  set_fact: "installer_cmdline = {{ installer_cmdline }} --enable-foreman-compute-vmware=true" 
  when: enable_vmware == true

- name: Configure IdM/IPA authentication if required
  set_fact: "installer_cmdline = {{ installer_cmdline }} --foreman-ipa-authentication=true"
  when: install_idm_client == true

- name: Configure CNAME used in certificates to {{ ansible_hostname }}
  set_fact: "installer_cmdline = {{ installer_cmdline }} --certs-cname={{ ansible_hostname }}"

- name: Configure FQDN used in certificates to {{ ansible_hostname }}
  set_fact: "installer_cmdline = {{ installer_cmdline }} --certs-node-fqdn={{ ansible_hostname }}"

- name: Configure custom certificates if they were generated - certificate file
  set_fact: "installer_cmdline = {{ installer_cmdline }} --certs-server-cert={{ server_crt_file }}"
  when: generate_certs == true

- name: Configure custom certificates if they were generated - csr file
  set_fact: "installer_cmdline = {{ installer_cmdline }} --certs-server-cert-req={{ server_csr_file }}"
  when: generate_certs == true

- name: Configure custom certificates if they were generated - key file
  set_fact: "installer_cmdline = {{ installer_cmdline }} --certs-server-key={{ server_key_file }}"
  when: generate_certs == true

- name: Configure custom certificates if they were generated - certificate file
  set_fact: "installer_cmdline = {{ installer_cmdline }} --certs-server-ca-cert={{ server_ca_file }}"
  when: generate_certs == true

- name: Configure foreman to manage IdM/IPA DNS
  set_fact: "installer_cmdline = {{ installer_cmdline }} --foreman-proxy-freeipa-remove-dns=true"
  when: install_idm_client == true

- name: Set the default administator information - email
  set_fact: "installer_cmdline = {{ installer_cmdline }} --foreman-admin-email={{ foreman_admin_email }}"

- name: Set the default administator information - admin first name
  set_fact: "installer_cmdline = {{ installer_cmdline }} --foreman-admin-firstname={{ foreman_admin_firstname }}"

- name: Set the default administator information - admin last name
  set_fact: "installer_cmdline = {{ installer_cmdline }} --foreman-admin-lastname={{ foreman_admin_lastname }}"

- name: Set the default administator information - admin username
  set_fact: "installer_cmdline = {{ installer_cmdline }} --foreman-admin-username={{ foreman_admin_username }}"

- name: Set the default administator information - admin password
  set_fact: "installer_cmdline = {{ installer_cmdline }} --foreman-admin-password={{ foreman_admin_password }}"

- name: Set the foreman base information - initial location
  set_fact: "installer_cmdline = {{ installer_cmdline }} --foreman-initial-location={{ foreman_initial_location }}"

- name: Set the foreman base information - initial organization
  set_fact: "installer_cmdline = {{ installer_cmdline }} --foreman-initial-organization= {{ foreman_initial_organization }}"

- name: Set up the foreman proxy service for the IdM/IPA realm if required
  set_fact: "installer_cmdline = {{ installer_cmdline }} --foreman-proxy-realm=true"
  when: foreman_proxy_realm == true

- name: Set up the foreman proxy - realm keytab
  set_fact: "installer_cmdline = {{ installer_cmdline }} --foreman-proxy-realm-keytab={{ foreman_proxy_realm_keytab }}"
  when: foreman_proxy_realm == true

- name: Set up the foreman proxy - realm principal
  set_fact: "installer_cmdline = {{ installer_cmdline }} --foreman-proxy-realm-principal={{ foreman_proxy_realm_principal }}"
  when: foreman_proxy_realm == true

- name: Set up the foreman proxy - realm provider
  set_fact: "installer_cmdline = {{ installer_cmdline }} --foreman-proxy-realm-provider={{ foreman_proxy_realm_provider }}"
  when: foreman_proxy_realm == true

- name: Setup TFTP if required
  set_fact: "installer_cmdline = {{ installer_cmdline }} --foreman-proxy-tftp=true"
  when: foreman_proxy_tftp == true

- name: Enable bare metal discovery if tftp is on
  set_fact: "installer_cmdline = {{ installer_cmdline }} --foreman-proxy-plugin-discovery-install-images=true"
  when: foreman_proxy_tftp == true

- name: Enable katello proxy for CDN if required - proxy url
  set_fact: "installer_cmdline = {{ installer_cmdline }} --katello-proxy-url={{ katello_proxy_url }}"

- name: Enable katello proxy for CDN if required - proxy port
  set_fact: "installer_cmdline = {{ installer_cmdline }} --katello-proxy-port={{ katello_proxy_port }}"

- name: Enable katello proxy for CDN if required - proxy username
  set_fact: "installer_cmdline = {{ installer_cmdline }} --katello-proxy-username={{ katello_proxy_username }}"

- name: Enable katello proxy for CDN if required - proxy password
  set_fact: "installer_cmdline = {{ installer_cmdline }} --katello-proxy-password={{ katello_proxy_password }}"

- debug:
    msg: "Preparing to execute command: {{ installer_cmdline }}"

- name: Installing Satellite - this will take about 10 minutes
  command: "{{ installer_cmdline }}"


