---
# This play sets up the main Satellite Server
# This must complete successfully before creating any capsule servers
# This play now uses the yml template method for generating the installation configuration
# Please see satellite-answers.default.yml in the template directory
#

- name: Deploy the configuration Template to foreman-installer directory (backup original)
  template:
    src: templates/satellite-answers.yaml.j2
    dest: /etc/foreman-installer/scenarios.d/satellite-answers.yaml
    backup: yes

- name: Install the Satellite Server
  command: "satellite-installer --scenario={{ scenario }}"

