---
# Set then fqdn, ip address, netmask on the idm_bootstrap adapter
#

- name: "Set the fqdn for this host: {{ idm_bootstrap_fqdn }}"
  command: "hostnamectl set-hostname {{ idm_bootstrap_fqdn }}"

- name: "Clean up any existing idm_bootstrap network connections for: {{ idm_bootstrap_con_name }}"
  command: "nmcli con delete {{ idm_bootstrap_con_name }}"
  ignore_errors: true

- name: "Reset the network configuration for: {{ idm_bootstrap_con_name }}"
  command: "nmcli con add save yes con-name {{ idm_bootstrap_con_name }} ifname {{ idm_bootstrap_adapter }}  type ethernet ip4  {{ idm_bootstrap_ip4 }}/{{ idm_bootstrap_prefix }} gw4 {{ idm_bootstrap_gateway }} ipv4.dns '{{ idm_bootstrap_dns }} 8.8.8.8'"

- name: "Bring the connection {{ idm_bootstrap_con_name }} online"
  command: "nmcli con up {{ idm_bootstrap_con_name }}"

- name: "Refreshing host facts"
    setup:

- name: "Test connectivity to our FQDN"
  wait_for:
    host: "{{ idm_bootstrap_fqdn }}"
    port: 22
    timeout: 10

- debug:
    msg: "Can reach system {{ idm_bootstrap_fqdn }} continuing..."


- name: "Test Connectivity to Google"
  wait_for:
    host: 8.8.8.8
    port: 53
    timeout: 10

- debug:
    msg: "Can reach the internet continuing..."

- debug:
    msg: "Building system {{ ansible_fqdn }}"
   

