---
# This play will configure the mandatory Content Views for the lab.
# This will create the views with the create_cv.yml play
#
# Define your mandatory content views in the satellite-servers variable file
# using a list
#
- name: Creating the specified MANDATORY COMPOSITE content views
  include_tasks: create_ccv.yml
  loop: "{{ lookup('dict', ccvs_mandatory) }}"

