---
# This role will perform the post installer tasks to get our Satellite running
#
# This role expects the manifest file on ansible control host where you are running 
# this script: override using the src_manifest_location variable
#
# First we need a manifest uploaded
# Next we need to specify repositories to synch (for our lab)
#  JBoss_A-MQ_Clients_1_RHEL_7_Server_RPMs_x86_64_7Server
#  JBoss_AMQ_Interconnect_1_RHEL_7_Server_RPMs_x86_64
#  JBoss_Core_Services_RHEL_7_Server_RPMs_x86_64
#  JBoss_Enterprise_Application_Platform_7_0_RHEL_7_Server_RPMs_x86_64_7Server
#  JBoss_Enterprise_Application_Platform_7_RHEL_7_Server_RPMs_x86_64_7Server
#  JBoss_Web_Server_3_RHEL_7_Server_RPMs_x86_64_7Server
#  Red_Hat_3scale_API_Management_Platform_2_0_RPMs_x86_64
#  Red_Hat_3scale_API_Management_Platform_2_2_RPMs_x86_64
#  Red_Hat_Ansible_Engine_2_6_RPMs_for_Red_Hat_Enterprise_Linux_7_Server_x86_64
#  Red_Hat_CloudForms_Management_Engine_5_7_RPMs_x86_64
#  Red_Hat_CloudForms_Management_Engine_5_8_RPMs_x86_64
#  Red_Hat_CloudForms_Management_Engine_5_9_RPMs_x86_64
#  Red_Hat_Enterprise_Linux_7_Server_-_Extras_RPMs_x86_64
#  Red_Hat_Enterprise_Linux_7_Server_-_Optional_RPMs_x86_64_7Server
#  Red_Hat_Enterprise_Linux_7_Server_-_RH_Common_RPMs_x86_64_7Server
#  Red_Hat_Enterprise_Linux_7_Server_-_Supplementary_RPMs_x86_64_7Server
#  Red_Hat_Enterprise_Linux_7_Server_Kickstart_x86_64_7_6
#  Red_Hat_Enterprise_Linux_7_Server_RPMs_x86_64_7Server
#  Red_Hat_Enterprise_Linux_Fast_Datapath_RHEL_7_Server_RPMs_x86_64_7Server
#  Red_Hat_Enterprise_Linux_High_Availability_for_RHEL_7_Server_RPMs_x86_64_7Server
#  Red_Hat_Enterprise_Linux_Resilient_Storage_for_RHEL_7_Server_RPMs_x86_64_7Server
#  Red_Hat_Enterprise_Virtualization_Hypervisor_7_RPMs_x86_64_7Server
#  Red_Hat_Enterprise_Virtualization_Management_Agents_for_RHEL_7_RPMs_x86_64_7Server
#  Red_Hat_Enterprise_Virtualization_Management_Agents_RPMs_x86_64_6Server
#  Red_Hat_Gluster_Storage_3_1_Big_Data_RPMs_x86_64_7Server
#  Red_Hat_Gluster_Storage_3_1_Console_RPMs_x86_64_7Server
#  Red_Hat_Gluster_Storage_3_1_Nagios_RPMs_x86_64_7Server
#  Red_Hat_Gluster_Storage_3_1_NFS_RPMs_x86_64_7Server
#  Red_Hat_Gluster_Storage_3_1_Samba_for_RHEL_7_Server_RPMs_x86_64_7Server
#  Red_Hat_Gluster_Storage_3_1_Server_RPMs_x86_64_7Server
#  Red_Hat_Gluster_Storage_3_1_Splunk_RPMs_x86_64_7Server
#  Red_Hat_JBoss_Data_Grid_7_1_RHEL_7_Server_RPMs_x86_64
#  Red_Hat_Mobile_Application_Platform_v4_4_RPMs_x86_64
#  Red_Hat_OpenShift_Application_Runtimes_Node_js_v10_RPMs_x86_64
#  Red_Hat_OpenShift_Application_Runtimes_Node_js_v8_RPMs_x86_64
#  Red_Hat_OpenShift_Container_Platform_3_11_RPMs_x86_64
#  Red_Hat_OpenShift_Container_Platform_3_9_RPMs_x86_64
#  Red_Hat_Satellite_6_4_for_RHEL_7_Server_RPMs_x86_64
#  Red_Hat_Satellite_Maintenance_6_for_RHEL_7_Server_RPMs_x86_64
#  Red_Hat_Satellite_Tools_6_4_for_RHEL_7_Server_RPMs_x86_64
#  Red_Hat_Software_Collections_RPMs_for_Red_Hat_Enterprise_Linux_7_Server_x86_64_7Server
#  Red_Hat_Storage_Native_Client_for_RHEL_7_RPMs_x86_64_7Server
#  Red_Hat_Virt_V2V_Tool_for_RHEL_7_RPMs_x86_64_7Server
#  Red_Hat_Virtualization_4_Management_Agents_for_RHEL_7_RPMs_x86_64_7Server
#  Red_Hat_Virtualization_Host_7_Build_RPMs_x86_64
#  Red_Hat_Virtualization_Host_7_RPMs_x86_64
#  Red_Hat_Virtualization_Manager_4_Tools_RHEL_7_Server_RPMs_x86_64
#  Red_Hat_Virtualization_Manager_v4_1_RHEL_7_Server_RPMs_x86_64
#  Red_Hat_Virtualization_Manager_v4_2_RHEL_7_Server_RPMs_x86_64
#  Single_Sign-On_7_1_RHEL_7_Server_RPMs_x86_64

# Prepare Content for builds
- include_task: upload_manifest.yml
- include_task: configure_mandatory_repositories.yml
- include_task: configure_optional_repositories.yml
- include_task: start_synchronization.yml
- include_task: create_environments.yml
- include_task: create_mandatory_cvs.yml
- include_task: create_optional_cvs.yml
- include_task: create_mandatory_ccvs.yml
- include_task: create_optional_ccvs.yml

# Discover Infrastructure
- include_task: configure_discovery.yml

