---
# This play will generate the required repositories for the OpenShift Container Platform Images product
#


    - name: Create the Product
      command: "hammer product create --name={{ product_name }} --label={{ product_label }} --organization={{ organization }} --description='{{ product_description }}"

    - name: Create the Repositories for the required images
      command: "hammer repository create --name={{ item.name }} --label={{ item.name }} --organization={{ organization }} --product={{ product_name }} --content-type=docker --docker-upstream-name={{ item.upstream_name }} --url='https://registry.redhat.io' --upstream-username={{ rhn_username }} --upstream-password={{ rhn_password }} --verify-ssl-on-sync=true"
      loop: "{{ repository_name }}"

    - name: Syncronize the Repositories asynchronously - we will queue them all.
      command: hammer repository synchronize --name={{ item.name }} --product={{ product_name }} --organization={{ organization }} --async
      loop: "{{ repository_name }}"

