---
# This task sets up virtwho on the Satellite server
#

- name: Install the virt-who binaries
  yum:
    name: virt-who
    state: latest

- name: Create the encypted cr_controller_password
  command: "virt-who-password --password={{ cr_controller_password }}"
  register: result

- name: Set the encrypted password
  set_fact: cr_controller_encrypted_password = {{ result.stdout_lines.1 }}

- name: Create the encrypted password for the Satellite admin
  command: "virt-who-password --password={{ foreman_admin_password }}"
  register: result

- name: Set the encrypted password
  set_fact: foreman_admin_encrypted_password = {{ result.stdout_lines.1 }}

- name: Create the virt-who configuration file
  template:
    src: virt-who.j2
    dest: /etc/virt-who.d/ansible.virtwho.conf

- name: Ensure the virt-who service is enabled
  service:
    name: virt-who
    enabled: true
    state: restarted 

