---
# This series of tasks removes a specified VMware virtual 
# machine from the target cluster -- ungracefully with 
# respect to the guest OS.
# #Blowfeld #NoMrBond #ForReal
#
# 

- name: "Powering off specified Windows Server system on VMware"
  vmware_guest:
    validate_certs: "{{ vmware_validate_certs }}"
    hostname: "{{ vmware_vcenter_host }}"
    username: "{{ vmware_vcenter_username }}"
    password: "{{ vmware_vcenter_password }}"
    datacenter: "{{ vmware_vcenter_datacenter }}"
    name: "{{ vm.vmware_vm_name }}"
    folder: "{{ vm.vmware_vm_folder }}"
    state: "poweredoff"
    cluster: "{{ vm.vmware_vm_cluster }}"

- name: "Delete specified Windows Server system on VMware"
  vmware_guest:
    validate_certs: "{{ vmware_validate_certs }}"
    hostname: "{{ vmware_vcenter_host }}"
    username: "{{ vmware_vcenter_username }}"
    password: "{{ vmware_vcenter_password }}"
    datacenter: "{{ vmware_vcenter_datacenter }}"
    name: "{{ vm.vmware_vm_name }}"
    folder: "{{ vm.vmware_vm_folder }}"
    state: "absent"
    cluster: "{{ vm.vmware_vm_cluster }}"

