# This playbook prepares the nodes  for the 
# deployment of openshift on the hosts
# defined in the specified inventory  

 - name: apply the install configuration to the masters
   hosts: openshift_masters
   become: yes

   roles:
   - master
