# This playbook prepares the nodes  for the 
# deployment of openshift on the hosts
# defined in the specified inventory  
---
- name: get configuration of all master nodes
  hosts: openshift_masters
  become: yes
  
  tasks:

  - name: Simply print out the FQDN
    debug:
      msg: "{{ ansible_fqdn }}"


- name: now see if we can do a Dynamic DNS update of the application record
  hosts: openshift_deployment_master
  become: yes
  

  tasks:

  - name: Create the list of master IPs
    set_fact: ocpdeploy_master_default_subdomain_addresses={{ groups['openshift_masters'] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) | list }}
    when: ocpdeploy_app_subdomain_lb_method == 'round-robin'
      
  - name: create application subdomain record in DNS for each master (round-robin)
    nsupdate:
      server: "{{ ocpdeploy_dnsupdate_server }}"
      zone: "{{ ocpdeploy_dnsupdate_zone }}"
      record: "{{ ocpdeploy_master_default_subdomain_wildcard }}"
      value: "{{ ocpdeploy_master_default_subdomain_addresses }}"	