---
# This playbook deploys an IPA signed certificate to a system
# This requires a kinit by the running process

- name: apply common configuration to service nodes
  hosts: service_targets

  roles:
    - kinitansible
    - ipasignedcert
