---
# Create repositories inside custom product
- name: Create repository
  katello_repository:
    username: "{{ foreman_admin_username }}"
    password: "{{ foreman_admin_password }}"
    server_url: "{{ foreman_foreman_url }}"
    verify_ssl: false
    name: "{{ item.name }}"
    product: "{{ product.name }}"
    organization: "{{ org_name }}"
    content_type: "yum"
    url: "{{ upstream }}"
    download_policy: "{{ upstream_policy | default ('immediate') }}"
    gpg_key: "{{ gpgkey_file  | default (omit) }}"
  loop: "{{ product.repos }}"
