---
galaxy_info:
  author: Paul Armstrong
  description: Prepare Foreman (Satellite) System for Lab Builder
  company: Red Hat, Inc.
  license: Apache License, Version 2.0
  min_ansible_version: 2.8
  platforms:
  - name: EL
    versions:
    - 7
  categories:
  - cloud
dependencies:

