---
# Ensure that the proper repositories are enabled.
# This playbook requires Satellite 6.4 

- name: Disable all exiting repositories
  command: subscription-manager repos --disable=*

- name: Enable the RHEL 7 Server repository
  command: subscription-manager repos --enable=rhel-7-server-rpms --enable=rhel-server-rhscl-7-rpms --enable=rhel-7-server-optional-rpms --enable=rhel-7-server-satellite-6.4-rpms --enable=rhel-7-server-satellite-maintenance-6-rpms --enable=rhel-7-server-ansible-2.7-rpms

#- name: Enable the RHEL Software Collections repository
#  command: subscription-manager repos --enable=rhel-server-rhscl-7-rpms

#- name: Enable the RHEL Optional RPMs Repository
#  command: subscription-manager repos --enable=rhel-7-server-optional-rpms

#- name: Enable the Satellite 6.4 RPMs Repository
#  command: subscription-manager repos --enable=rhel-7-server-satellite-6.4-rpms

#- name: Enable the Satellite 6.4 Maintenance Repository
#  command: subscription-manager repos --enable=rhel-7-server-satellite-maintenance-6-rpms

#- name: Enable the Ansible 2.6 or Better Repository
#  command: subscription-manager repos --enable=rhel-7-server-ansible-2.7-rpms

- name: Ensure the release is not set
  command: subscription-manager release --unset

- name: Clean the yum metadata
  command: yum clean all

- name: Update the system
  yum:
    name: '*'
    state: latest

- name: Install the Satellite RPM packages
  yum:
    name: satellite
    state: latest
