---
galaxy_info:
  author: Paul Armstrong
  description: Deploy and Configure IdM for Lab Builder
  company: Red Hat, Inc.
  license: Apache License, Version 2.0
  min_ansible_version: 2.7
  platforms:
  - name: EL
    versions:
    - 7
  categories:
  - cloud
dependencies:

