---
# tasks file for sync_plans
- name: Create sync plan
  katello_sync_plan:
    username: "{{ foreman_admin_username }}"
    password: "{{ foreman_admin_password }}"
    server_url: "{{ foreman_foreman_url }}"
    verify_ssl: false
    organization: "{{ org_name }}"
    interval: "{{ item.sync_interval }}"
    enabled: true
    sync_date: "{{ item.sync_date_time }}"
    products: "{{ item.sync_products }}"
    name: "{{ item.name }}"
  loop: "{{ sync_plans }}"
