# This playbook prepares the nodes  for the 
# deployment of openshift on the hosts
# defined in the specified inventory  

 - name: clean up incorrect docker logical volume 
   hosts: all
   become: yes

   tasks:

   - name: Delete /dev/vg_root/lv_docker
     lvol:
       vg: vg_root
       lv: lv_docker
       state: absent
       force: yes

