---
# tasks file for organization
- name: Upload manifest for initial organization
  katello_manifest:
    username: "{{ foreman_admin_username }}"
    password: "{{ foreman_admin_password }}"
    server_url: "{{ foreman_foreman_url }}"
    verify_ssl: false
    organization: "{{ foreman_initial_organization }}"
    manifest_path: "{{ manifest_src_location }}"
    state: present

block:
  - name: Create alternate organization
    foreman_organization:
      username: "{{ foreman_admin_username }}"
      password: "{{ foreman_admin_password }}"
      server_url: "{{ foreman_foreman_url }}"
      verify_ssl: false
      name: "{{ item.name }}"
      state: present

  - name: Upload alt-org manifest
    katello_manifest:
      username: "{{ foreman_admin_username }}"
      password: "{{ foreman_admin_password }}"
      server_url: "{{ foreman_foreman_url }}"
      verify_ssl: false
      organization: "{{ item.name }}"
      manifest_path: "{{ item.manifest_path }}"
      state: present

loop: "{{ auxiliary_organizations }}"
