---
# This is debug code and will get moved appropriately at a later date
# Issue: PyOpenSSL on base RHEL 7.6 is 0.13. For ansible CSR generation we need
# PyOpenSSL 0.15 or better. 
#
# Options: 
# - Install python 3.x using Software Collections and run 
#   anisble from within Software Collections python 3 shell.
#
# - Wait Until 8. :-)
#   
# Workaround: run the commands as we have done manually in the past.
#
# openssl genrsa \
#   -des3 \
#   -out $HOSTNAME.pem \
#   -passout file:/etc/ipa/private/passout.txt 4096
#
# openssl rsa \
#   -in /etc/ipa/private/$HOSTNAME.pem \
#   -out /etc/ipa/private/$HOSTNAME.password.key \
#   -passin file:/etc/ipa/private/passout.txt 
#
# openssl req \
#   -new \
#   -key /etc/ipa/private/$HOSTNAME.password.key \
#   -out /etc/ipa/private/$HOSTNAME.csr \
#   -subj "/C=CA/ST=Ontario/L=Toronto/O=PARMSTRONG.CA/OU=Lab/CN=$HOSTNAME/subjectAltName=$HOSTNAME"

# This functions as expected
- name: Generate a private key
  openssl_privatekey:
    path: "{{ ipa_server_pem_file }}"
    passphrase: "{{ ipa_rsa_key_pass }}"
    cipher: "DES3"
    force: yes

- name: Get an external use key
  command: "openssl rsa -in {{ ipa_server_pem_file }} -out {{ ipa_server_key_file }} -passin pass:{{ ipa_rsa_key_pass }}"

- name: Generate the CSR with subjectAltNames set
  command: "openssl req -new -passin pass:{{ ipa_rsa_key_pass }} -key {{ ipa_server_key_file }} -out {{ ipa_server_csr_file }} -subj '/C={{ ipa_country_name }}/ST={{ ipa_prov_name }}/L={{ ipa_locality_name }}/O={{ ipa_organization_name }}/OU={{ ipa_ou_name }}/CN={{ ansible_fqdn }}/subjectAltName={{ ansible_fqdn }}'"


