---
# Prepare the IdM Realm for use with Foreman
# This creates the realm capsule user and downloads a key the appropriate directory
#
# cd /etc/foreman-proxy/
# foreman-prepare-realm admin realm-63-capsule
# chown foreman-proxy:foreman-proxy /etc/foreman-proxy/freeipa.keytab
# check the keytab by performing the following task kinit -kt /etc/foreman-proxy/freeipa.keytab realm-63-capsule

- name: Launch prepare realm
  expect: 
    command: "foreman-prepare-realm admin {{ foreman_proxy_realm_principal }}"
    Password for admin@{{ ansbile_domain | upper }}: "{{ idm_admin }}"
  register: result

- debug: 
    msg: "{{ result.stdout }}"

- name: Move the keytab to the foreman-proxy directory
  copy:
    src: ./freeipa.keytab
    dest: /etc/foreman-proxy/freeipa.keytab
    owner: foreman-proxy
    group: foreman-proxy
    remote_src: yes

- name: Test the new keytab
  command: "kinit -kt /etc/foreman-proxy/freeipa.keytab {{ foreman_proxy_realm_principal }}"
  register: result

- set_fact:
    is_success: "{{ result.stdout }}"

- debug:
    msg: "Success"
  when: is_success == ""

