---
# Prepare the IdM Realm for use with Foreman
# This creates the realm capsule user and downloads a key the appropriate directory
#
# cd /etc/foreman-proxy/
# foreman-prepare-realm admin realm-63-capsule
# chown foreman-proxy:foreman-proxy /etc/foreman-proxy/freeipa.keytab
# check the keytab by performing the following task kinit -kt /etc/foreman-proxy/freeipa.keytab realm-63-capsule
#
# expect requires pexpect >=3.3 
# Not available without software collections
#
# - name: Launch prepare realm
#   expect: 
#     command: "foreman-prepare-realm admin {{ foreman_proxy_realm_principal }}"
#     responses:
#       'Password for admin@{{ ansbile_domain | upper }}:': "{{ idm_admin }}"
#   register: result
- name: Clean up old keytabs
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/foreman-proxy/freeipa.keytab
    - /root/freeipa.keytab

- name: kinit admin
  shell: echo "{{ idm_admin }}" | kinit admin
  check_mode: no

- name: Launch Prepare Realm
  shell: echo "{{ idm_admin }}" | /usr/sbin/foreman-prepare-realm admin "{{ foreman_proxy_realm_principal }}"
  check_mode: no
#  changed_when: "1 != 1"
  register: result

- debug:
    msg: "{{ result.stdout }}"
 
- name: Wait for keytab generation and retrieval
  wait_for:
    path: /root/freeipa.keytab

- name: Ensure the foreman-proxy directory exists
  file:
    path: /etc/foreman-proxy
    state: directory

- name: Move the keytab to the foreman-proxy directory
  copy:
    src: /root/freeipa.keytab
    dest: /etc/foreman-proxy/freeipa.keytab
    owner: foreman-proxy
    group: foreman-proxy
    remote_src: yes

- name: Test the new keytab
  command: "kinit -kt /etc/foreman-proxy/freeipa.keytab {{ foreman_proxy_realm_principal }}"
  register: result

- set_fact:
    is_success: "{{ result.stdout }}"

- debug:
    msg: "Success"
  when: is_success == ""

- name: copy the ipa ca-certificates to the trust directory
  copy:
    src: /etc/ipa/ca.crt
    dest: /etc/pki/ca-trust/source/anchors/ipa.crt
    remote_src: yes
    owner: root
    group: root
    mode: '0644'

- name: enable the trust
  command: "update-ca-trust enable"

- name: update the trust
  command: "update-ca-trust"

# we will restart the foreman-proxy several times, this is optional at this point
# we could use notify... if we were really concerned... which we are not.
