---
# Ensure that chronyd is installed and that time is synchronized.
# Later we will set this up to sync with IdM
# This is simply the bootstrap or initial install process
# We will have a configure idm client role that comes later to 
# change the configuration to its final settings
#

- name: Install chrony for accurate time keeping
  yum:
    name: chrony
    state: latest

- name: Start the chronyd service with default settings
  service:
    name: chronyd
    state: started
    enabled: true

## If you wish to override default time services, do it here
#  otherwise, the IdM server will become the time server.

- name: Install the SOS Report package while we are at it...
  yum:
    name: sos
    state: latest

