---
# This play gives you the opportunity to install any additional tools that you might want
# It is really here because I forgot stuff in the iso :-) so, handy...
#
# Provide the utilities packages as a list in the satellite-servers group_vars file
# I am putting in bind-utils and screen
# screen has been replaced by tmux in future releases of RHEL

- name: "Ensure RHEL 7 rpms repo is enabled"
  command: "subscription-manager repos --enable=rhel-7-server-rpms"
  
- name: "Install Lab Builder utilities"
  yum:
    name: "{{ utils }}"
    state: latest
  vars:
    utils:
      - pexpect

- name: "Install user specified utilities."
  yum:
    name: "{{ bootstrap_add_utils }}"
    state: latest
  when: "(bootstrap_add_utils | length)  > 0"

