---
# setup the server for the installation of Satellite or Capsule
#

- import_tasks: repositories.yml
- import_tasks: install_utilities.yml
- import_tasks: install_chronyd.yml
- import_tasks: sat_firewalld_config.yml
- import_tasks: install_satellite.yml

- import_tasks: install_idm_client.yml
  when: ipa_install_client == true

- import_tasks: generate_certs.yml
  when: ipa_generate_certs == true and ipa_install_client == true

- import_tasks: check_certs.yml
  when: ipa_generate_certs == true and ipa_install_client == true

- import_tasks: foreman_prepare_realm.yml
  when: ipa_generate_certs == true and ipa_install_client == true

