---
- name: DEBUGGING FOREMAN HOST IPA BASED HTTP CSR GENERATION
  hosts: localhost
  vars:
    ipa_server_pem_file: "/etc/ipa/private/{{ ansible_fqdn }}.pem"
    ipa_rsa_key_pass: "zinYCvtxhq82"
    ipa_server_key_file: "/etc/ipa/private/{{ ansible_fqdn }}.key"
    ipa_server_csr_file: "/etc/ipa/private/{{ ansible_fqdn }}.csr"
    ipa_server_crt_file: "/etc/ipa/private/{{ ansible_fqdn }}.crt"
    ipa_organization_name: "{{ ansible_domain | upper }}"
    ipa_ou_name: "Demo Lab"
    ipa_locality_name: "Hespeler"
    ipa_prov_name: "ON"
    ipa_country_name: "CA"
    ipa_email_address: "admin@{{ ansible_domain }}"
    ipa_service_type: "HTTP"

  tasks:

  - include_tasks: debug_certs.yml
