---
# Ensure that the proper repositories are enabled.
# This playbook requires Satellite 6.4 

- name: Disable all exiting repositories
  command: subscription-manager repos --disable=*

- name: Enable the required Satellite repositories
  command: subscription-manager repos --enable=rhel-7-server-rpms --enable=rhel-server-rhscl-7-rpms --enable=rhel-7-server-satellite-6.6-rpms --enable=rhel-7-server-satellite-maintenance-6-rpms --enable=rhel-7-server-ansible-2.8-rpms --enable=rhel-7-server-optional-rpms

- name: Ensure the release is not set
  command: subscription-manager release --unset

- name: Clean the yum metadata
  command: yum clean all
  args:
    warn: false


