---
# Ensure that the proper repositories are enabled.
# This playbook requires Satellite 6.4 

- name: Disable all exiting repositories
  command: subscription-manager repos --disable=*

- name: Enable the required Satellite repositories
  command: "subscription-manager repos --enable={{ item.repoid }}"
  loop: "{{ satellite_repos }}"

- name: Ensure the release is not set
  command: subscription-manager release --unset

- name: Clean the yum metadata
  command: yum clean all
  args:
    warn: false


