---
# Configure firewalld for Satellite.
# NOTE: other service ports may be opened when aspects of the configuration are changed
# firewalld service port operations are additive unless configured otherwise
# firewall ports below are defaulting to open for all Satellite features as 
# this play is initially designed for a lab or POC environment.
# This play can be adapted conditionals for more coordinated feature control.

- name: Ensure that firewalld is installed
  yum:
    name: firewalld
    state: latest

- name: Ensure that iptables is not running and is masked
  systemd:
    name: iptables
    state: stopped
    enabled: no
    masked: yes
  ignore_errors: true

- name: Ensure that the Firewalld service is enabled and running
  systemd:
    name: firewalld
    state: started
    enabled: yes
    masked: no

- name: Configure Firewalld services and ports for Satellite Services
  firewalld:
    service: RH-Satellite-6
    permanent: true
    state: enabled
    zone: "{{ sat_firewalld_zone }}"

- name: Configure Firewalld services and ports for Satellite - Libvirt (if required)
  firewalld:
    port: 16514/tcp
    permanent: true
    state: enabled
    zone: "{{ sat_firewalld_zone }}"

- name: Configure Firewalld services and ports for Satellite - Performance Co-Pilot
  firewalld:
    port: 44321/tcp
    permanent: true
    state: enabled
    zone: "{{ sat_firewalld_zone }}"


- name: Ensure that the firewall services are reloaded
  command: firewall-cmd --reload

