---
# Enable the correct repos for the install
# Default today enable all repos for any type of install

- name: Disable all repos
  command: subscription-manager repos --disable=*

- name: Enable RHEL 7 repos
  command: subscription-manager repos --enable=rhel-7-server-rpms

- name: Enable Extras repos (ansible)
  command: subscription-manager repos --enable=rhel-7-server-extras-rpms

- name: Enable HA repos (clustered NFS or CIFS support)
  command: subscription-manager repos --enable=rhel-ha-for-rhel-7-server-rpms

- name: Enable main Gluster repo
  command: subscription-manager repos --enable=rh-gluster-3-for-rhel-7-server-rpms

- name: Enable Gluster Big Data repo
  command: subscription-manager repos --enable=rh-gluster-3-big-data-for-rhel-7-server-rpms

- name: Enable Gluster Splunk repo
  command: subscription-manager repos --enable=rh-gluster-3-splunk-for-rhel-7-server-rpms

- name: Enable Gluster Nagios repo
  command: subscription-manager repos --enable=rh-gluster-3-nagios-for-rhel-7-server-rpms

- name: Enable Gluster NFS Ganesha repo
  command: subscription-manager repos --enable=rh-gluster-3-nfs-for-rhel-7-server-rpms

- name: Enable Gluster CIFS repo
  command: subscription-manager repos --enable=rh-gluster-3-samba-for-rhel-7-server-rpms

