---
# tasks file for rhcdn_repositories
- name: Enable RH CDN-based repositories
  katello_repository_set:
    username: "{{ foreman_admin_username }}"
    password: "{{ foreman_admin_password }}"
    server_url: "https://{{ foreman_foreman_url }}"
    verify_ssl: false
    organization: "{{ org_name }}"
    label: "{{ item.name }}"
    repositories:
      - releasever: "{{ item.release | default (omit)}}"
        basearch: "{{ item.arch | default (omit)}}"
    state: enabled
  loop: "{{ repos }}"

- name: Get all repositories
  foreman_search_facts:
    username: "{{ foreman_admin_username }}"
    password: "{{ foreman_admin_password }}"
    server_url: "https://{{ foreman_foreman_url }}"
    verify_ssl: false
    resource: repositories
  register: repositories

- name: Set download policy
  katello_repository:
    username: "{{ foreman_admin_username }}"
    password: "{{ foreman_admin_password }}"
    server_url: "https://{{ foreman_foreman_url }}"
    verify_ssl: false
    organization: "{{ org_name }}"
    name: "{{ item.name }}"
    download_policy: immediate
    content_type: yum
    product: "{{ item.product.name }}"
  loop: "{{ repositories.resources }}"

- name: Kick off repository Sync tasks
  katello_sync:
    username: "{{ foreman_admin_username }}"
    password: "{{ foreman_admin_password }}"
    server_url: "https://{{ foreman_foreman_url }}"
    verify_ssl: false
    product: "{{ item.product.name }}"
    repository:  "{{ item.name }}"
    organization: "{{ org_name }}"
  loop: "{{ repositories.resources }}"
  when: item.url  # Not all repositories have a URL
  async: 999999
  poll: 0
  register: repo_sync_sleeper

- name: Wait until all Syncs have finished
  async_status:
    jid: "{{ repo_sync_sleeper_item.ansible_job_id }}"
  loop: "{{ repo_sync_sleeper.results }}"
  loop_control:
    loop_var: repo_sync_sleeper_item
  when: repo_sync_sleeper_item.ansible_job_id is defined  # Skip items that were skipped in the previous task
  register: async_job_result
  until: async_job_result.finished
  # We want to give ourselves a maximum of 6 hours. The timer resets every
  # time an async job completes. This may need to be adjusted.
  retries: 2160
  delay: 10
