---
# This set of tasks adds the repositories to a custom product
#

- name: Determine if the repo already exists
  command: "hammer repository info --name={{ cpr.name }} --product={{ cp.name | quote }} --organization={{ cp.org | quote }}"
  register: cpr_exists
  ignore_errors: true

- block:
  - name: Create the Repositories for the required container images
    command: "hammer repository create --name={{ cpr.name }} --label={{ cpr.name }} --organization={{ cp.org | quote }} --product={{ cp.name | quote }} --content-type={{ cpr.repository_content_type }} --docker-upstream-name={{ cpr.upstream_name }} --url={{ cpr.url }} --upstream-username={{ cpr.username }} --upstream-password={{ cpr.password }} --verify-ssl-on-sync=true"
    when: "cpr.repository_content_type == 'docker'"

  - name: Create the Repositories for the required file or yum content
    command: "hammer repository create --name={{ cpr.name }} --label={{ cpr.name }} --organization={{ organization | quote }} --product={{ product_name | quote }} --content-type={{ cpr.repository_content_type }} --url={{ cpr.url }} --upstream-username={{ cpr.username }} --upstream-password={{ cpr.password }} --verify-ssl-on-sync=true"
    when: "(cpr.repository_content_type == 'yum' or cpr.repository_content_type == 'file')"

  - name: Syncronize the Repositories immediately.
    command: "hammer repository synchronize --name={{ cpr.name | quote }} --product={{ cp.name | quote }} --organization={{ cp.org | quote }}"
  when: "cpr_exists.stdout == ''"


