---
# Configure the Special Operating Systems defined.
#

- name: "Finalize Configuration of any system defined Operating Systems."
  include_tasks: update_special_os.yml
  loop: "{{ oss_special }}"
  loop_control:
    loop_var: "sos"
  when: "oss_special is defined"
