---
# This play will configure the mandatory Content Views for the lab.
# This will create the views with the create_cv.yml play
#
# Define your mandatory content views in the satellite-servers variable file
# using a list
#
- name: Creating the specified content views
  include_tasks: create_ccv.yml
  loop: "{{ ccvs_mandatory }}"
  loop_control:
    loop_var: ccv

# Publish requires the cv loop variable. 
# Lets hope we don't crash here.
- name: Publish the specified content views
  include_tasks: publish_cv.yml
  loop: "{{ ccvs_mandatory }}"
  loop_control:
    loop_var: cv

