---
# This playbook configures the mandatory media defined in the
# {{ playbook_dir }}/vars/sat_vars.yml file
#

- name: Configure the specified mandatory media.
  include_tasks: create_media.yml
  loop: "{{ media_mandatory }}"
  loop_control:
    loop_var: md

