---
# This playbook configures the mandatory partition tables
#
# NOTE: the files referenced in the sat_vars.yml file
# for mandatory partition tables are located in the template directory
# of the foreman_post role. Optional partition table files may be 
# placed in the same directory or a custom path may be defined.
# Also, if no variables are present, the file will simply
# be loaded to foreman/satellite as is
#
- name: Create the mandatory partition tables defined
  include_tasks: create_ptable.yml
  loop: "{{ ptables_mandatory }}"
  loop_control:
    loop_var: ptable
  when: "ptables_mandatory is defined"

