---
# This play will configure the mandatory Content Views for the lab.
# This will create the views with the create_cv.yml play
#
# Define your mandatory content views in the satellite-servers variable file
# using a list
#
- name: Creating the specified custom products. 
  include_tasks: create_custom_product.yml
  loop: "{{ custom_products }}"
  loop_control:
    loop_var: cp


