---
# This playbook configures the mandatory discovery rules 
#
- name: Create the mandatory discovery rules 
  include_tasks: create_discovery_rule.yml
  loop: "{{ drules_mandatory }}"
  loop_control:
    loop_var: drule
  when: "drules_mandatory is defined"

