---
# This play will configure the mandatory Content Views for the lab.
# This will create the views with the create_cv.yml play
#
# Define your mandatory content views in the satellite-servers variable file
# using a list
#
- name: Creating the specified content views
  include_tasks: create_cv.yml
  loop: "{{ cvs_optional }}"
  loop_control:
    loop_var: cv

- name: Publish the specified content views
  include_tasks: publish_cv.yml
  loop: "{{ cvs_optional }}"
  loop_control:
    loop_var: cv

