---
# This playbook configures the optional partition tables
#
# NOTE: ensure that the file paths referenced in the sat_vars.yml file
# for your partition tables actually exist and are located in the 
# template directory of the foreman_post role or you defined a custom 
# path for the file in sat_vars.yml, otherwise the task will fail
# Also, if no variables are present, the file will simply
# be loaded to foreman/satellite as is
#
- name: Create the mandatory partition tables defined
  include_tasks: create_ptable.yml
  loop: "{{ ptables_optional }}"
  loop_control:
    loop_var: ptable
  when: "ptables_optional is defined"
