---
# This play will generate the required repositories for the custom products if any.
# 

- name: Determine if the Custom Product exists already
  command: "hammer product info --organization={{ cp.org | quote }} --name={{ cp.name | quote }}"
  register: cp_exists
  ignore_errors: true

- name: Create the Product {{ cp.name }}
  command: "hammer product create --name={{ cp.name }} --label={{ cp.label }} --organization={{ cp.org | quote }} --description={{ cp.desc | quote }}"
  when: "cp_exists.stdout == ''"

- name: Create the Repositories required for the custom product.
  include_tasks: add_custom_product_repos.yml
  loop: "{{ cp.repository_name }}"
  loop_control: 
    loop_var: cpr

