---
# This task creates an individual configuration template from specified paramters
# Call this task with loop_var: ct
#
# Specify the list as ctemplate_mandatory or ctemplate_optional in the vars file
#
# 
- name: Create temporary file
  tempfile:
    state: file
    suffix: temp
  register: output

# NOTE: Jinja2 and Foreman templating seem to be exclusive and can co-exist in the same file.
- name: Apply any ansible templating defined in the configuration template
  template:
    src: "{{ ct.path }}"
    dest: "{{ output.path }}"

- name: Delete the existing instance of the configuration template
  command: "hammer template delete --name={{ ct.name | quote }} --organization={{ ct.organization | quote }} --location={{ ct.location | quote }}"
  ignore_errors: true

# Attach to operating system later. During OS Congfig as many to many. Let the OS take from what's available.
# The only fly in the ointment is the partially configured OS we have right now
# this is likely from not including the RHEL 7.6 repository as part of the sync or its a bug... 
# it will add some processing time, but I will try it to see the result.
# Depending, this may necessitate a matching effort like we did with sync plans (kind of Satellite specific as we auto create some things...)
#
- name: Create configuration template definition as new initial version
  command: "hammer template create --name={{ ct.name | quote }} --organization={{ ct.organization | quote }} --location={{ ct.location | quote }} --file={{ output.path | quote }} --type={{ ct.type | quote }} --locked={{ ct.locked | quote }} --audit-comment={{ ct.audit_comment | quote }}"

