---
# This play creates an individual content view from specified paramters
# Call this with a dictionary defining the content-view.
#
# Specify the list as cvs_mandatory or cvs_optional in the vars file
#
# We ARE NOT using auto-publish for composites as we will control that 
# through the monthly content configuration with Tower
#
# Creating the content view is many layered:
# - create the view
# - add the repositories
# - add the filters
# - add any ansible content
# 
- name: Determine if the Content View Exists
  command: "hammer --output=json content-view info --organization={{ cv.org | quote }} --name={{ cv.name | quote }}"
  register: cv_exists
  ignore_errors: true

- name: Creating Content View {{ cv.name }} in Organization {{ cv.org }}
  command: "hammer content-view create --name={{ cv.name | quote }} --description={{ cv.desc | quote }} --organization={{ cv.org | quote }}"
  when: "cv_exists.stdout == ''"

# update overwrites any existing repository information
# Note, repositories is a comma separated list, no spaces on either side comma or only picks up the first one.
- name: Add the repositories to the Content View
  command: "hammer content-view update --name={{ cv.name | quote }} --organization={{ cv.org | quote }} --repositories={{ cv.repositories | join(',') | quote }}"

# Add the filters
- name: Add the filters to the Content View
  include_tasks: create_cv_filter.yml
  loop: "{{ cv.filters }}"
  loop_control:
    loop_var: cvf

