---
# This play creates an individual composite content view from specified cvs
# Call this with a dictionary defining the composite content-view.
#
# Specify the list as ccvs_mandatory or ccvs_optional in the vars file
#
# We ARE NOT using auto-publish for composites as we will control that 
# through the monthly content configuration with Tower
#
# Creating the content view is many layered:
# - create the view
# - add the repositories
# - add the filters
# - add any ansible content
# 
- name: Determine if the Composite Content View {{ ccv.name }} exists
  command: "hammer --output=json content-view info --organization={{ ccv.org | quote }} --name={{ ccv.name | quote }}"
  register: cv_exists
  ignore_errors: true

# We can create the view and then update afterwards
- name: Creating Composite Content View {{ ccv.name }} in Organization {{ ccv.org }}
  command: "hammer content-view create --composite --name={{ ccv.name | quote }} --description={{ ccv.desc | quote }} --organization={{ ccv.org | quote }}"
  when: "cv_exists.stdout == ''"

# Determine the list of Component IDs given the Names of the Content Views
# We will always go with latest versions as we just published them in order to create them
# This always has to be dynamic as the IDs can change and hammer call doesn't take content view version names or offer a "latest" flag. 
- set_fact:
    ccvv_ids: ""

- name: Determine the list of Component Content View Version IDs to add
  include_tasks: get_component_ids.yml
  loop: "{{ ccv.components }}"
  loop_control:
    loop_var: ccvc

# This should contain the unquoted list of component content view version ids...
# - debug:
#    msg: "{{ ccvv_ids }}"

# update overwrites any existing Component-id information
# Note, repositories is a comma separated list, no spaces on either side comma or only picks up the first one.
- name: Add the Component Content View Versions to the Composite Content View
  command: "hammer content-view update --name={{ ccv.name | quote }} --organization={{ ccv.org | quote }} --component-ids={{ ccvv_ids | quote }}"

