---
# This role will perform the post installer tasks to get our Satellite running
#
# This role expects the manifest file on ansible control host where you are running 
# this script: override using the src_manifest_location variable
#
# First we need a manifest uploaded
# Next we need to specify repositories to synch (for our lab)

# Prepare Content for builds
# hammer should get set up for root automatically when configured in template for foreman install
# for some reason the installer adds a space on the end of the password. I can't track it down in 
# this code, so, I am updating the file the installer creates in setup_hammer.yml

- import_tasks: "{{ role_path }}/tasks/setup_hammer.yml"
  tags:
    - import_content

- import_tasks: "{{ role_path }}/tasks/upload_manifest.yml" 
  tags: 
    - import_content

- import_tasks: "{{ role_path }}/tasks/configure_mandatory_repositories.yml "
  tags: 
    - import_content

- import_tasks: "{{ role_path }}/tasks/configure_optional_repositories.yml"
  tags: 
    - import_content

- import_tasks: "{{ role_path }}/tasks/configure_custom_products.yml"
  tags:
    - import_content
    
- import_tasks: "{{ role_path }}/tasks/start_synchronization.yml "
  tags: 
    - import_content

- import_tasks: "{{ role_path }}/tasks/configure_lifecycle_environments.yml"
  tags: 
    - import_content

- import_tasks: "{{ role_path }}/tasks/configure_mandatory_cvs.yml"
  tags: 
    - import_content

- import_tasks: "{{ role_path }}/tasks/configure_optional_cvs.yml"
  tags: 
    - import_content

- import_tasks: "{{ role_path }}/tasks/configure_mandatory_ccvs.yml"
  tags: 
    - import_content

- import_tasks: "{{ role_path }}/tasks/configure_optional_ccvs.yml"
  tags: 
    - import_content

- import_tasks: "{{ role_path }}/tasks/configure_mandatory_sync_plans.yml"
  tags:
    - import_content

- import_tasks: "{{ role_path }}/tasks/configure_optional_sync_plans.yml"
  tags:
    - import_content

- import_tasks: "{{ role_path }}/tasks/attach_sync_plans.yml"
  tags:
    - import_content

# Configure the Provisioning Components
#

- import_tasks: "{{ role_path }}/tasks/configure_mandatory_media.yml"
  tags:
    - config_pv

- import_tasks: "{{ role_path }}/tasks/configure_optional_media.yml"
  when: "setup_optional_media == true"
  tags:
    - config_pv

- import_tasks: "{{ role_path }}/tasks/configure_mandatory_ptables.yml"
  tags:
    - config_pv

- import_tasks: "{{ role_path }}/tasks/configure_optional_ptables.yml"
  tags:
    - config_pv

- import_tasks: "{{ role_path }}/tasks/configure_mandatory_prov_templates.yml"
  tags:
    - config_pv

- import_tasks: "{{ role_path }}/tasks/configure_optional_prov_templates.yml"
  tags:
    - config_pv

# Ready for OS creation
# NOTE: RHEL OS is "special" - it is created by Satellite, you must include the version specific kickstart
# as a synchronized repository to get the deployment to work with base components
# Personally, I am of the opinion that this should happen in the background or don't include the OS..
# Work completely when you sync 7Server only. No half measures. #OffSoapBox
#
- import_tasks: "{{ role_path }}/tasks/configure_special_oss.yml"
  tags:
    - config_pv

- import_tasks: "{{ role_path }}/tasks/configure_mandatory_oss.yml"
  tags:
    - config_pv

- import_tasks: "{{ role_path }}/tasks/configure_optional_oss.yml"
  tags:
    - config_pv

# * ActivationKeys
# Again, mandatory (to meet base config), optional (to add to the config - also failing will not stop build till the end of the phase)
- import_tasks: "{{ role_path }}/tasks/configure_mandatory_aks.yml"
  tags:
    - config_pv

- import_tasks: "{{ role_path }}/tasks/configure_optional_aks.yml"
  tags:
    - config_pv

# * Domains
# Ditto
- import_tasks: "{{ role_path }}/tasks/configure_mandatory_domains.yml"
  tags:
    - config_pv

- import_tasks: "{{ role_path }}/tasks/configure_optional_domains.yml"
  tags:
    - config_pv

# * Realms
- import_tasks: "{{ role_path }}/tasks/configure_mandatory_realms.yml"
  tags:
    - config_pv

- import_tasks: "{{ role_path }}/tasks/configure_optional_realms.yml"
  tags:
    - config_pv

# * Subnets
- import_tasks: "{{ role_path }}/tasks/configure_mandatory_subnets.yml"
  tags:
    - config_pv

- import_tasks: "{{ role_path }}/tasks/configure_optional_subnets.yml"
  tags:
    - config_pv

# * Discovery - boot to discovery image on timeout
- import_tasks: "{{ role_path }}/tasks/build_pxe_defaults.yml"
  tags:
    - config_pv


# * Create Host Groups - we need these to attach to the discovery rules
#
- import_tasks: "{{ role_path }}/tasks/configure_mandatory_host_groups.yml"
  tags:
    - config_pv

- import_tasks: "{{ role_path }}/tasks/configure_optional_host_groups.yml"
  tags:
    - config_pv


# Note you may define any additional discovery rules here that are required for your
# implementation in Phase 3 Infrastructure
# For others baremetal systems that may part of your platform deployment
# include discovery rules in your Phase 4 configuration
#
- import_tasks: "{{ role_path }}/tasks/configure_mandatory_discovery_rules.yml"
  tags:
    - config_pv

- import_tasks: "{{ role_path }}/tasks/configure_optional_discovery_rules.yml"
  tags:
    - config_pv

- import_tasks: "{{ role_path }}/tasks/poweron.yml"
  tags:
    - config_pv


