---
# This role will perform the post installer tasks to get our Satellite running
#
# This role expects the manifest file on ansible control host where you are running 
# this script: override using the src_manifest_location variable
#
# First we need a manifest uploaded
# Next we need to specify repositories to synch (for our lab)

# Prepare Content for builds
# hammer should get set up for root automatically when configured in template for foreman install
# for some reason the installer adds a space on the end of the password. I can't track it down in 
# this code, so, I am updating the file the installer creates in setup_hammer.yml
- import_tasks: "{{ role_path }}/tasks/setup_hammer.yml"
  tags:
    - import_content

- import_tasks: "{{ role_path }}/tasks/upload_manifest.yml" 
  tags: 
    - import_content

- import_tasks: "{{ role_path }}/tasks/configure_mandatory_repositories.yml "
  tags: 
    - import_content

- import_tasks: "{{ role_path }}/tasks/configure_optional_repositories.yml"
  tags: 
    - import_content

- import_tasks: "{{ role_path }}/tasks/start_synchronization.yml "
  tags: 
    - import_content

- import_tasks: "{{ role_path }}/tasks/configure_lifecycle_environments.yml"
  tags: 
    - import_content

- import_tasks: "{{ role_path }}/tasks/configure_mandatory_cvs.yml"
  tags: 
    - import_content

- import_tasks: "{{ role_path }}/tasks/configure_optional_cvs.yml"
  tags: 
    - import_content

- import_tasks: "{{ role_path }}/tasks/configure_mandatory_ccvs.yml"
  tags: 
    - import_content

- import_tasks: "{{ role_path }}/tasks/configure_optional_ccvs.yml"
  tags: 
    - import_content

- import_tasks: "{{ role_path }}/tasks/configure_custom_products.yml"
  tags: 
    - import_content


# Configure the Provisioning Components
#

- import_tasks: "{{ role_path }}/tasks/configure_mandatory_media.yml"
  tags:
    - config_pv

- import_tasks: "{{ role_path }}/tasks/configure_optional_media.yml"
  tags:
    - config_pv

- import_tasks: "{{ role_path }}/tasks/configure_mandatory_ptables.yml"
  tags:
    - config_pv

- import_tasks: "{{ role_path }}/tasks/configure_optional_ptables.yml"
  tags:
    - config_pv


