---
# This is a media content specific task called dynamically based
# on a media definition in {{ playbook_dir }}/vars/sat_vars.yml
#

# Ensure that the local path for the RHVH content exists
# Download the content from Red Hat for the latest RHVH install
#
- name: Create the directory for hosting the media image
  file: 
    state: directory
    path: "/var/www/pub/rhvh"
    mode: 755
    owner: apache
    group: apache

# Download the content from source
# We are fudging this currently as Satellite does not provide a RHEL kickstart
# The content needs to be downloaded from the CDN to be current we are going 
# to approach this another way. We will include the hypervisor ISO, the manager
# OVA and the CFME OVA on the bootstrap disk. Once the hypervisor is up, it can
# perform its own updates of the hypervisors.
# This now becomes a simple file call. Because this will now be 
# on the bootstrap image in the root directory, it is a local call.
# We have tonnes of disk space.
#

- name: Copy the DVD content to the target directory
  copy: 
    src: /root/rhvh/media/ 
    dest: /var/www/pub/rhvh/

- name: Copy the boot files - vmlinuz - to tftp directory
  copy:
    src: /root/rhvh/vmlinuz
    dest: /var/lib/tftpboot/boot/rhvh.42.vmlinuz

- name: Copy the boot files - initrd.img - to tftp directory
  copy:
    src: /root/rhvh/initrd.img
    dest: /var/lib/tftpboot/boot/rhvh.42.initrd.img


