
- name: "Everybody say Pong"
  hosts: all
  remote_user: root

  tasks:

  - name: "And a one and a two and a..."
    ping:


- name: "And all the girls say..."
  hosts: foreman
  remote_user: root

  tasks:

  - name: "Oooh. Oh. oh. oh. Oh. oh. Oh. Oh."
    ping:


- name: "And all my dudes say..."
  hosts: build_master
  remote_user: root

  tasks:

  - name: "Oooh. Oh. oh. oh. Oh. oh. Oh. Oh."
    ping:


