---
##############################################

- name: "PHASE 1 - BEGIN bootstrap foreman_only"
  hosts: foreman
  remote_user: root
  gather_facts: yes

  tasks:
  
  - name: "Phase initialization - {{ ansible_fqdn }} "
    include_tasks: play_init.yml
    tags:
      - config_pv

  - name: "Did we really pick up the variables?"
    debug:
      msg: "{{ media_mandatory | to_nice_yaml }}"
    tags:
      - config_pv

  - name: "Apply ONLY role of foreman_post to existing foreman"
    include_role:
      name: foreman_post
    tags:
      - config_pv

  - name: "END PHASE 1 - bootstrap complete"
    file:
      path: "{{ locks_dir }}/bootstrap_complete"
      state: touch
    tags:
      - config_pv


# PHASE 2 - bootstrap 2 CONDITIONAL
# AUTO
#   PROCEED
# MANUAL
#   UNLOCK VAR FILES
#   TERMINATE
## PHASE 2 - bootstrap 2 CONDITIONAL 


## PHASE 2 - bootstrap 2
#
#
# BEGIN ANSIBLE MANAGED BLOCK
# BEGIN needed to indent - prepare.yml
# END needed to indent - prepare.yml
# END ANSIBLE MANAGED BLOCK
