---
##############################################

- name: "PHASE 1 - BEGIN bootstrap foreman_only"
  hosts: foreman
  remote_user: root
  gather_facts: yes

  tasks:
  
  - name: "Who is the Foreman?"
    debug:
      msg: "{{ play_hosts }}"

  - name: "Ping the foreman host"
    ping:

  - pause:
      seconds: 30


  - name: "DIE DIE DIE! "
    fail:
    when: "'foreman.labbuilder.lab' not in play_hosts"

  - name: "Phase initialization - {{ ansible_fqdn }} "
    include_tasks: play_init.yml

  - name: "Apply role of foreman_pre to {{ ansible_fqdn }}"
    include_role:
      name: foreman_pre

  - name: "Apply role of foreman to {{ ansible_fqdn }}"
    include_role:
      name: foreman
  
  - name: "Apply role of foreman_post to {{ ansible_fqdn }}"
    include_role:
      name: foreman_post

  - name: "Wait for build_master"
    wait_for:
      path: "{{ locks_dir }}/build_master_complete"

  - name: "Wait for foreman"
    wait_for:
      path: "{{ locks_dir }}/foreman_complete"

  - name: "END PHASE 1 - bootstrap complete"
    file:
      path: "{{ locks_dir }}/bootstrap_complete"
      state: touch

## PHASE 2 - bootstrap 2 CONDITIONAL
# AUTO
#   PROCEED
# MANUAL
#   UNLOCK VAR FILES
#   TERMINATE
## PHASE 2 - bootstrap 2 CONDITIONAL 


## PHASE 2 - bootstrap 2
#
#
# BEGIN ANSIBLE MANAGED BLOCK
# BEGIN needed to indent - prepare.yml
# END needed to indent - prepare.yml
# END ANSIBLE MANAGED BLOCK
