---
# This is a playbook that will generate random encrypted 
# passwords for lab_builder.
# List the password variables that you would like generated 
# and their length below. Passwords will be generated and encrypted
# using the password file located in password_file
# This password_file should contain the master password and be stored in
# a private,protected location outside of the repository.
# Only with the file with the right password and matching encrypted file
# will you be able to successfully run plays using the generated variables
#
- name: "Install utilities"
  yum:
    name: expect
    state: latest

- name: create the output file
  file: 
    name: "{{ output_file }}"
    state: touch

- name: create the passwords, encrypt them and write them to the file
  include_tasks: site_write_encrypted_variables.yml
  loop: "{{ variable_list }}"
  loop_control:
    loop_var: var

- name: log the encypted passwords
  command: "cat {{ output_file }}"
  register: output

- debug:
    msg: "{{ output.stdout }}"

