---
# This is a playbook that will generate random encrypted 
# passwords for lab_builder.
# List the password variables that you would like generated 
# and their length below. Passwords will be generated and encrypted
# using the password file located in password_file
# This password_file should contain the master password and be stored in
# a private,protected location outside of the repository.
# Only with the file with the right password and matching encrypted file
# will you be able to successfully run plays using the generated variables
#
- name: "Install utilities"
  yum:
    name: expect
    state: latest

# Does the password file already exist
- name: stat the output file
  stat:
    path: "{{ output_file }}"
  register: of


- set_fact: 
    epf_overwrite: true
  when: 
    - "of.stat.exists == true"
    
- set_fact: 
    epf_overwrite: false
  when:
    - "phase_name is defined"
    - "phase_name == 'test_foreman_post'"

# Is overwrite password on

- name: create the output file
  file: 
    name: "{{ output_file }}"
    state: touch
  when: "epf_overwrite == true"

- name: create the passwords, encrypt them and write them to the file
  include_tasks: site_write_encrypted_variables.yml
  loop: "{{ variable_list }}"
  loop_control:
    loop_var: var
  when: "epf_overwrite == true"

# Change overwrite passwords to off 
# We only want to do this once in a site build
#
- set_fact:
    epf_overwrite: false

