---
# This playbook generates a snapshot for a VM managed by a vcenter server
  - name: Check the hosts
    debug: 
      msg: "Host {{ item }} will be snapped"
 
  - name: Create a snapshot
    vmware_guest_snapshot:
      state: present
      # Weird how Tower requires the quotes and ansible does not...
      datacenter: '{{ datacenter_name }}'
      folder: '{{ snapshot_folder_name }}'
      hostname: '{{ vcenter_server }}'
      name: '{{ item }}'
      snapshot_name: '{{ snap_name }}'
