---
# this set of tasks will update the vmtools for the 
# supplied system
# pass items in with the loop_var as vgtu

- name: Upgrade the vmware tools installation
  vmware_guest_tools_upgrade:
    name: "{{ vmware_vm_name }}"
    hostname: "{{ vmware_vcenter_host }}"
    username: "{{ vmware_vcenter_username }}"
    password: "{{ vmware_vcenter_password }}"
    datacenter: "{{ vmware_vcenter_datacenter }}"
    validate_certs: "{{ vmware_validate_certs }}"
    folder: "{{ vmware_vm_folder }}"
  delegate_to: localhost

